### PR TITLE
Small fix to mediation_contrast

### PR DESCRIPTION
**Pull request by jbrochar**
Fix for several small issues about mediation analysis and RFT:
- the formula for the X-M effect wasn't correct in mediationAnalysis0.m
- the calls to the matlab function cdf(**) and icdf(**) were relying on default parameters values, that are not provided in recent Matlab version
- an approximation to zero caused a 0/0 computation in RFT_Pval.m, I added an exception to return the correct p-value

### CODE REVIEW

**Comment by jdaunize** [comment]
Jules,
Can you document your change please?
Jean.

**Comment by jbrochar** [comment]
The relevant change are already commented (see the commit messages). Nevertheless there is probably a mistake somewhere from my side as I don't understand why my "pull" show up here (all the  	" Merge remote-tracking branch 'upstream/master' " just correspond to me pulling the most recent changes to my local repository) ...

**Comment by lionel-rigoux** [comment]
The individual commit messages will disapear when the pull request is validated. In order to avoid polluting the master history with all the details of your progress (in particular all the merges you had to do to keep up with the upstream repo), the whole set of changes contained in your pull request will be appplied to the master as one unique commit (squash merge). The  message of this commit will be  by default set to the descrition text you provide. 
So you should edit the description above to summarize the feature provided by your contribution.

**Comment by jbrochar** [comment]
Ok I'll do it, thanks.

**Comment by lionel-rigoux** [comment]
If you want to avoid the annoying `Merge remote-tracking branch 'upstream/master' `, switch on the rebase option when you pull.

**Comment by lionel-rigoux** [comment]
I think it would be better if you developed directly in the MBB-team/VBA-toolbox instead of in your fork (you're part of the team, don't be shy!).
Add the  MBB-team/VBA-toolbox in your list of remotes:
`git remote add mbb-remote git@github.com:MBB-team/VBA-toolbox.git`
 then
`git push mbb-remote master:jbrochar`

**Comment by lionel-rigoux** [comment]
Is this pull request still on hold? Should I try to squash it in the development branch?

**Comment by jbrochar** [comment]
For me it should have been incorporated a while ago.

**Comment by lionel-rigoux** [comment]
@jbrochar: could you open the same pull request toward the developement branch? I am a bit reluctant about puting everything in the master...

**Comment by lionel-rigoux** [comment]
nevermind, found how to do it

**Pull request merged**
